services:
  postgres:
    image: postgres:16-alpine
    container_name: academy-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: academy
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
